*** Variables ***
${STANDARD_USERNAME}       standard_user
${STANDARD_PASSWORD}       secret_sauce

${LOCKED_USERNAME}         locked_out_user

${INVALID_USERNAME}        invalid_user
${INVALID_PASSWORD}        invalid_password

${LOCKED_ERROR}            Epic sadface: Sorry, this user has been locked out.
${INVALID_ERROR}           Epic sadface: Username and password do not match any user in this service